/* Generated By:JavaCC: Do not edit this line. ComputinConstants.java */
package RussoComputin;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ComputinConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int TIPOINT = 6;
  /** RegularExpression Id. */
  int TIPOFLOAT = 7;
  /** RegularExpression Id. */
  int TIPOSTRING = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int MAIS = 13;
  /** RegularExpression Id. */
  int MENOS = 14;
  /** RegularExpression Id. */
  int MULT = 15;
  /** RegularExpression Id. */
  int DIVIS = 16;
  /** RegularExpression Id. */
  int IGUAL = 17;
  /** RegularExpression Id. */
  int NOT = 18;
  /** RegularExpression Id. */
  int MAIOR = 19;
  /** RegularExpression Id. */
  int MENOR = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int EQ = 23;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 24;
  /** RegularExpression Id. */
  int VIRGULA = 25;
  /** RegularExpression Id. */
  int ABREPAREN = 26;
  /** RegularExpression Id. */
  int FECHAPAREN = 27;
  /** RegularExpression Id. */
  int ABRECHAVE = 28;
  /** RegularExpression Id. */
  int FECHACHAVE = 29;
  /** RegularExpression Id. */
  int ID = 30;
  /** RegularExpression Id. */
  int EXPRESSAO_INT = 31;
  /** RegularExpression Id. */
  int EXPRESSAO_FLOAT = 32;
  /** RegularExpression Id. */
  int EXPRESSAO_STRING = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"suka_blyat\"",
    "\"marikhuana\"",
    "\"missil\"",
    "\"stroka\"",
    "\"kommunizm\"",
    "\"ne_rabotayet\"",
    "\"mezhdu_serpom_i_molotom\"",
    "\"tsar_bomba\"",
    "\"dobavleniye\"",
    "\"vychitaniye\"",
    "\"umnozheniye\"",
    "\"razdeleniye\"",
    "\"ravnyy\"",
    "\"net\"",
    "\"bolshe\"",
    "\"neznachitelnyy\"",
    "\"zatem\"",
    "\"ili\"",
    "\"uk\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<ID>",
    "<EXPRESSAO_INT>",
    "<EXPRESSAO_FLOAT>",
    "<EXPRESSAO_STRING>",
  };

}
