/* Generated By:JavaCC: Do not edit this line. RussoComputinConstants.java */
package Compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RussoComputinConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TIPOINT = 5;
  /** RegularExpression Id. */
  int TIPOFLOAT = 6;
  /** RegularExpression Id. */
  int TIPOSTRING = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int FOR = 11;
  /** RegularExpression Id. */
  int PRINT = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int STAR = 15;
  /** RegularExpression Id. */
  int SLASH = 16;
  /** RegularExpression Id. */
  int ASSIGN = 17;
  /** RegularExpression Id. */
  int SEMICOLON = 18;
  /** RegularExpression Id. */
  int LPAREN = 19;
  /** RegularExpression Id. */
  int RPAREN = 20;
  /** RegularExpression Id. */
  int LBRACE = 21;
  /** RegularExpression Id. */
  int RBRACE = 22;
  /** RegularExpression Id. */
  int CONSTANT = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;
  /** RegularExpression Id. */
  int ID = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"tseloye\"",
    "\"veshchestvennoe\"",
    "\"stroka\"",
    "\"esli\"",
    "\"inache\"",
    "\"poka\"",
    "\"dlya\"",
    "\"pechat\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<ID>",
  };

}
